# Azure Databricks Build Pipeline
# azure-pipelines.yml

trigger:
- azureDevOps

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.8'
  inputs:
    versionSpec: 3.8

- script: |
    python -m pip install --upgrade pip
    pip install requests setuptools wheel pylint black flake8 flake8-comprehensions pep8-naming mypy pytest pyspark httpagentparser pandas numpy
  displayName: 'Load Python Dependencies'

- checkout: self
  persistCredentials: true
  clean: true

- script: git checkout azureDevOps
  displayName: 'Get Latest Branch'

- script: |
    python -m pytest

  displayName: 'Run Python Unit Tests for library code'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
    publishRunAttachments: true

- script: |
    python3 -m build --sdist --wheel
    ls dist/
  displayName: 'Build Python Wheel for Libs'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'DatabricksBuild'