trigger:
- azureDevOps

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python 3.8'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
      echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)\bin;$(PATH)"

- script: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade build setuptools twine
    pip install -r requirements.txt
    python -m pytest
    python -m build
  displayName: 'Install dependencies'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'caaswx-feed1'

- script: |
   twine upload -r "caaswx-feed1" --config-file $(PYPIRC_PATH) dist/*