# This is a basic workflow to help you get started with Actions

name: PyLint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Running Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint, format, and type-check
      run: |
        flake8 --config=.flake8 .
        black --diff --check --verbose .
        # exit-zero treats all errors as warnings.
        # diverting from the standard 79 character line length in
        # accordance with this:
        # https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds
        flake8 . --count --exit-zero --statistics --select=E,F,W,C90
    - name: Unit Tests
      run: |
        python -m pytest

