name: PyLint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Running Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' 
        java-version: '11'
    - name: Set up Python 3.8.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Unit Tests
      run: |
        python -m pytest

    - name: black
      run: |
        black --line-length=79 --diff --check --verbose .
    - name: flake8
      run: |
        flake8 . --count --statistics --select=E,F,W,C90



